# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Warnings currently triggered by your code
- ignore: {name: "Use module export list"}
- ignore: {name: "Use camelCase"}
- ignore: {name: "Redundant $"}
- ignore: {name: "Use null"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use fmap"}
- ignore: {name: "Use let"}
- ignore: {name: "Use foldr"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use unless"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Use :"}
- ignore: {name: "Use guards"}
- ignore: {name: "Fuse concatMap/map"}
- ignore: {name: "Move brackets to avoid $"}
- ignore: {name: "Use const"}
- ignore: {name: "Use isNothing"}
- ignore: {name: "Use zipFrom"}
- ignore: {name: "Use zipWithFrom"}
- ignore: {name: "Use drop1"}
- ignore: {name: "Use dropEnd1"}
- ignore: {name: "Use headDef"}
- ignore: {name: "Use pure"}
