sudo: required

matrix:
  include:
  - env: GHCVER=7.4.2
  - env: GHCVER=7.6.3
  - env: GHCVER=7.8.4
  - env: GHCVER=7.10.3
  - env: GHCVER=8.0.2
  - env: GHCVER=8.2.1
  - env: GHCVER=8.4.1
  - env: GHCVER=head
  - os: osx
  allow_failures:
  - os: osx

script:
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
