build: off
cache:
- "c:\\sr -> appveyor.yml" ##

test_script:
- Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/neil/master/appveyor.ps1').Content
- stack exec -- neil --version
