on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -sSL https://raw.github.com/ndmitchell/neil/master/github.sh | sh
        env:
          GHCVER: '8.10'
          TRAVIS_OS_NAME: linux
