on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.10', '8.8', '8.6', '8.4', '8.2', '8.0']
        include:
          - os: windows-latest
          - os: macOS-latest

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          $APPDATA/.cabal/packages
          $APPDATA/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
    - run: curl -sSL https://raw.github.com/ndmitchell/neil/master/github.sh | sh
