on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.10.2', '8.8.4', '8.6.5']
        include:
          - os: windows-latest
            ghc: latest
          - os: macOS-latest
            ghc: latest

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.cabal/bin
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
    - run: curl -sSL https://raw.github.com/ndmitchell/neil/master/github.sh | sh
