on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macOS-latest, windows-latest]
        ghc: ['8.10.2'] # , '8.8.4', '8.6.5']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
    - run: curl -sSL https://raw.github.com/ndmitchell/neil/master/github.sh | sh
      env:
        GHCVER: ${{ matrix.ghc }}
        TRAVIS_OS_NAME: linux
