name: release
on:
  # Match when pushing tags v*, i.e. v1.0, v20.15.10
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          SUFFIX: x86_64-linux.tar.gz
        - os: windows-latest
          SUFFIX: x86_64-windows.zip
        - os: macOS-latest
          SUFFIX: x86_64-osx.tar.gz

    steps:
    - uses: rishabhgupta/split-by@v1
      id: username_repo
      with:
        string: ${{ github.repository }} # e.g. ndmitchell/neil
        split-by: '/'

    - uses: rishabhgupta/split-by@v1
      id: refs_tags_version
      with:
        string: ${{ github.ref }} # e.g. refs/tags/v0.11.1.1
        split-by: '/'

    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
    - uses: ndmitchell/neil@master
      with:
        make-release: true

    - uses: actions/create-release@v1
      id: create-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: dist/bin/${{ steps.username_repo.outputs._1 }}-${{ steps.refs_tags_version.outputs._2 }}-${{ matrix.SUFFIX }}
        asset_name: ${{ steps.username_repo.outputs._1 }}-${{ steps.refs_tags_version.outputs._2 }}-${{ matrix.SUFFIX }}
        asset_content_type: application/zip
